// @vitest-environment node
import {afterEach,beforeEach,describe,expect,it} from 'vitest'
import {listenPreviewHost} from './preview-host.mjs'

let server,base
beforeEach(async()=>{server=await listenPreviewHost(0);base=`http://127.0.0.1:${server.address().port}`})
afterEach(async()=>{if(server)await new Promise(resolve=>server.close(resolve));server=null})
const api=(path,init)=>fetch(`${base}/wrss/api${path}`,init)

describe('preview WeRSS Host',()=>{
 it('pages and mutates articles while retaining retry behavior',async()=>{const list=await (await api('/articles?offset=10&limit=10')).json();expect(list.data.list).toHaveLength(10);expect(list.data.total).toBeGreaterThan(10);const id=list.data.list[0].id;await api(`/articles/${id}/favorite?is_favorite=true`,{method:'PUT'});const favorites=await (await api('/articles?only_favorite=true&search=&offset=0&limit=50')).json();expect(favorites.data.list.some(article=>article.id===id)).toBe(true);await fetch(`${base}/wrss/mock/fail-next`,{method:'POST'});expect((await api('/articles?limit=10')).status).toBe(503);expect((await api('/articles?limit=10')).status).toBe(200)})

 it('requires explicit preview scan and confirmation',async()=>{await api('/auth/qr/code');await api('/auth/qr/status');await api('/auth/qr/status');let info=await (await api('/sys/info')).json();expect(info.data.wx.login).toBe(false);let qr=await (await api('/auth/qr/status')).json();expect(qr).toEqual({code:0,data:expect.objectContaining({login_status:false,scanned:false})});await api('/mock/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'scan'})});qr=await (await api('/auth/qr/status')).json();expect(qr.data).toMatchObject({login_status:false,scanned:true});await api('/mock/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'confirm'})});info=await (await api('/sys/info')).json();expect(info.data.wx.login).toBe(true);await api('/auth/wechat/logout',{method:'POST'});info=await (await api('/sys/info')).json();expect(info.data.wx.login).toBe(false)})

 it('fills an explicitly empty library with the latest ten after a source update',async()=>{await fetch(`${base}/wrss/mock/empty`,{method:'POST'});let list=await (await api('/articles?offset=0&limit=10&search=')).json();expect(list.data).toMatchObject({list:[],total:0});const submitted=await (await api('/mps/update/demo-1?start_page=0&end_page=1')).json();expect(submitted.data.status).toBe('queued');await api(`/mps/update/tasks/${submitted.data.task_id}`);const completed=await (await api(`/mps/update/tasks/${submitted.data.task_id}`)).json();expect(completed.data).toMatchObject({status:'succeeded',added:10});list=await (await api('/articles?offset=0&limit=10&search=')).json();expect(list.data.list).toHaveLength(10);expect(list.data.total).toBe(10);expect(list.data.list.map(article=>article.publish_time)).toEqual([...list.data.list.map(article=>article.publish_time)].sort((a,b)=>b-a))})

 it('blocks the remaining queue and new submissions after a preview 200013',async()=>{await fetch(`${base}/wrss/mock/sync-mode`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'rate-limit'})});const first=(await (await api('/mps/update/demo-1')).json()).data,second=(await (await api('/mps/update/demo-2')).json()).data;await api(`/mps/update/tasks/${first.task_id}`);const blocked=await (await api(`/mps/update/tasks/${first.task_id}`)).json();expect(blocked.data).toMatchObject({status:'blocked',code:200013});expect((await (await api(`/mps/update/tasks/${second.task_id}`)).json()).data).toMatchObject({status:'blocked',code:200013});const info=await (await api('/sys/info')).json();expect(info.data.article_sync).toMatchObject({recent_error_code:200013});expect((await (await api('/mps/update/demo-3')).json()).data).toMatchObject({status:'blocked',code:200013})})

 it.each([['network',50200],['unauthorized',40101]])('surfaces %s sync failures as structured tasks',async(mode,code)=>{await fetch(`${base}/wrss/mock/sync-mode`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode})});const task=(await (await api('/mps/update/demo-1')).json()).data;await api(`/mps/update/tasks/${task.task_id}`);const failed=await (await api(`/mps/update/tasks/${task.task_id}`)).json();expect(failed.data).toMatchObject({status:'failed',code})})

 it('reports a successful sync with no new articles',async()=>{const task=(await (await api('/mps/update/demo-1')).json()).data;await api(`/mps/update/tasks/${task.task_id}`);const done=await (await api(`/mps/update/tasks/${task.task_id}`)).json();expect(done.data).toMatchObject({status:'succeeded',added:0,message:'抓取完成，没有新增文章'})})

 it('mutates sources, creates collected articles, cleans deletes, and serves declared exports',async()=>{const before=(await (await api('/mps?offset=0&limit=100')).json()).data.total;const added=await (await api('/mps',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mp_id:'biz',mp_name:'Added',avatar:''})})).json();expect(added.data.sync_task).toMatchObject({mp_id:added.data.id,status:'queued'});expect((await (await api('/mps?kw=Added&offset=0&limit=10')).json()).data.total).toBe(1);expect((await (await api('/mps?offset=0&limit=100')).json()).data.total).toBe(before+1);await api('/mps/featured/article',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:'https://example.com/new'})});expect((await (await api('/articles?search=单篇收录&offset=0&limit=10')).json()).data.total).toBe(1);const article=(await (await api('/articles?offset=0&limit=1')).json()).data.list[0];await api(`/articles/${article.id}`,{method:'DELETE'});const cleaned=await (await api('/articles/clean',{method:'DELETE'})).json();expect(cleaned.data.deleted_count).toBe(1);expect((await api('/tools/export/articles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({export_pdf:true})})).status).toBe(422);const created=await (await api('/tools/export/articles',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({export_csv:true})})).json();const download=await api(`/tools/export/download?filename=${created.data.filename}`);expect(download.headers.get('content-type')).toContain('text/csv');expect(await download.text()).toContain('title,id');const opml=await api('/export/mps/opml');expect(opml.headers.get('content-type')).toContain('opml');expect(await opml.text()).toContain('<opml')})
})
