import {createServer as createHttpServer} from 'node:http'
const now=()=>Math.floor(Date.now()/1000)
function createData(){const sources=Array.from({length:23},(_,i)=>({id:`demo-${i+1}`,faker_id:Buffer.from(String(i+1)).toString('base64'),mp_name:['机器之心','数字生命卡兹克','新智元'][i%3]+` ${i+1}`,mp_intro:'AI 产品、研究与创作方法',mp_cover:'',status:i%7?1:0,article_count:12+i}));const articles=sources.flatMap((s,si)=>Array.from({length:12},(_,i)=>({id:`${s.id}-${i+1}`,title:`${s.mp_name}：第 ${i+1} 篇精选文章`,mp_id:s.id,mp_name:s.mp_name,publish_time:now()-(si*20+i)*3600,summary:'预览 Host 提供的示例文章',content:`# ${s.mp_name}\n\n这是预览正文。`,url:`https://example.com/${s.id}/${i+1}`,has_content:i%3!==0,status:i%11===0?'updating':'active',is_read:0,is_favorite:i%4===0?1:0,favorite_at:i%4===0?now()-(si*20+i)*3600:null})));return{sources,articles}}
function headers(origin='*'){return{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'content-type'}}
function json(res,status,value,origin){res.writeHead(status,headers(origin));res.end(status===204?'':JSON.stringify(value))}
async function body(req){const chunks=[];for await(const chunk of req)chunks.push(chunk);const text=Buffer.concat(chunks).toString('utf8');try{return JSON.parse(text||'{}')}catch{return{}}}
export function createPreviewHost(){
 const {sources,articles}=createData();let failNext=false,emptyMode=false,syncMode='normal',qrVersion=1,qrExpires=0,mockLogin=false,mockScanned=false,sourceSequence=sources.length,syncSequence=0;const exportFiles=new Map([['preview.md',{content:'# 公众号预览导出\n',type:'text/markdown; charset=utf-8'}]]),exports=[{filename:'preview.md',path:'preview.md',size:exportFiles.get('preview.md').content.length,created_time:new Date().toISOString(),mp_id:''}];const tasks=new Map(),syncTasks=new Map(),activeSyncBySource=new Map();const articleSync={cooldown_until:0,recent_error_code:null,recent_error_message:''}
 return createHttpServer(async(req,res)=>{const u=new URL(req.url||'/',`http://${req.headers.host}`),origin=req.headers.origin||'*';if(req.method==='OPTIONS')return json(res,204,{},origin)
  if(u.pathname==='/vk/v1/integrations/wrss')return json(res,200,{state:'running',summary:'预览公众号 Host 已就绪',reason_code:null,progress_log:[],version:'preview',size_label:'预览数据',ui_url:`http://${req.headers.host}/preview`},origin)
  if(u.pathname==='/wrss/mock/fail-next'&&req.method==='POST'){failNext=true;return json(res,200,{ok:true},origin)}
  if(u.pathname==='/wrss/mock/empty'&&req.method==='POST'){articles.splice(0);emptyMode=true;return json(res,200,{ok:true},origin)}
  if(u.pathname==='/wrss/mock/sync-mode'&&req.method==='POST'){const data=await body(req);syncMode=String(data.mode||'normal');return json(res,200,{ok:true,mode:syncMode},origin)}
  if(u.pathname.startsWith('/wrss/source-avatar/')&&req.method==='GET'){const label=decodeURIComponent(u.pathname.split('/').pop()||'?').slice(0,2),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><rect width="100%" height="100%" fill="#263d70"/><text x="48" y="58" text-anchor="middle" fill="white" font-size="22">${label}</text></svg>`;res.writeHead(200,{'content-type':'image/svg+xml','cache-control':'no-store','access-control-allow-origin':origin});return res.end(svg)}
  if(u.pathname==='/wrss/article-image'&&req.method==='GET'){const remote=new URL(u.searchParams.get('url')||'https://invalid.test');if(!['mmbiz.qpic.cn','mmbiz.qlogo.cn','mmecoa.qpic.cn'].includes(remote.hostname))return json(res,400,{error:'文章图片地址无效'},origin);const svg='<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"><rect width="100%" height="100%" fill="#263d70"/></svg>';res.writeHead(200,{'content-type':'image/svg+xml','cache-control':'no-store','access-control-allow-origin':origin});return res.end(svg)}
  if(failNext&&u.pathname.startsWith('/wrss/api/')){failNext=false;return json(res,503,{error:'预览请求失败，请重试'},origin)}
  if(u.pathname==='/wrss/qr-image'){const svg='<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240"><rect width="100%" height="100%" fill="#fff"/><text x="120" y="110" text-anchor="middle" font-size="18">演示二维码</text><text x="120" y="140" text-anchor="middle" font-size="13">不可扫码授权</text></svg>';res.writeHead(200,{'content-type':'image/svg+xml','cache-control':'no-store','access-control-allow-origin':origin});return res.end(svg)}
  if(u.pathname==='/wrss/api/tools/export/download'){const filename=u.searchParams.get('filename')||'',file=exportFiles.get(filename);if(!file)return json(res,404,{error:'导出文件不存在'},origin);res.writeHead(200,{'content-type':file.type,'content-disposition':`attachment; filename="${filename}"`,'access-control-allow-origin':origin});return res.end(file.content)}
  const p=u.pathname.startsWith('/wrss/api/')?u.pathname.slice('/wrss/api'.length):''
  if(p==='/mps'&&req.method==='GET'){const q=u.searchParams.get('kw')||'',status=u.searchParams.get('status'),offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||10),list=sources.filter(s=>(!q||s.mp_name.includes(q))&&(status===null||String(s.status)===status));return json(res,200,{code:0,data:{list:list.slice(offset,offset+limit),total:list.length}},origin)}
  const search=p.match(/^\/mps\/search\/(.+)$/);if(search&&req.method==='GET'){const q=decodeURIComponent(search[1]),list=sources.filter(s=>s.mp_name.includes(q)).map(s=>({fakeid:s.faker_id,nickname:s.mp_name,round_head_img:s.mp_cover,signature:s.mp_intro}));return json(res,200,{code:0,data:{list,total:list.length}},origin)}
  if(p==='/articles'&&req.method==='GET'){const q=u.searchParams.get('search')||'',only=u.searchParams.get('only_favorite')==='true',mp=u.searchParams.get('mp_id')||'',status=u.searchParams.get('status'),has=u.searchParams.get('has_content');let list=articles.filter(a=>(status==='deleted'?a.status==='deleted':a.status!=='deleted')&&(!status||status==='deleted'||a.status===status)&&(!only||a.is_favorite)&&(!mp||a.mp_id===mp)&&(!q||a.title.includes(q)||a.mp_name.includes(q))&&(has===null||a.has_content===(has==='true')));list.sort((a,b)=>only?(b.favorite_at||0)-(a.favorite_at||0):b.publish_time-a.publish_time);const offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||10);return json(res,200,{code:0,data:{list:list.slice(offset,offset+limit),total:list.length}},origin)}
  const favorite=p.match(/^\/articles\/([^/]+)\/favorite$/);if(req.method==='PUT'&&favorite){const a=articles.find(x=>x.id===decodeURIComponent(favorite[1]));if(!a)return json(res,404,{error:'文章不存在'},origin);a.is_favorite=u.searchParams.get('is_favorite')==='true'?1:0;a.favorite_at=a.is_favorite?now():null;return json(res,200,{code:0,message:'收藏状态已更新',is_favorite:!!a.is_favorite},origin)}
  const read=p.match(/^\/articles\/([^/]+)\/read$/);if(req.method==='PUT'&&read){const a=articles.find(x=>x.id===decodeURIComponent(read[1]));if(!a)return json(res,404,{error:'文章不存在'},origin);a.is_read=u.searchParams.get('is_read')==='true'?1:0;return json(res,200,{code:0,is_read:!!a.is_read},origin)}
  if(['/articles/clean','/articles/clean_duplicate_articles','/articles/clean-old'].includes(p)&&req.method==='DELETE'){const before=articles.length;if(p==='/articles/clean'){for(let i=articles.length-1;i>=0;i--)if(articles[i].status==='deleted')articles.splice(i,1)}else if(p==='/articles/clean-old'){const cutoff=now()-Number(u.searchParams.get('days')||30)*86400;for(let i=articles.length-1;i>=0;i--)if(articles[i].publish_time<cutoff)articles.splice(i,1)}else{const seen=new Set();for(let i=articles.length-1;i>=0;i--){const key=`${articles[i].mp_id}:${articles[i].title}`;if(seen.has(key))articles.splice(i,1);else seen.add(key)}}return json(res,200,{code:0,data:{deleted_count:before-articles.length},message:`已清理 ${before-articles.length} 篇文章`},origin)}
  const articleMatch=p.match(/^\/articles\/([^/]+)(?:\/(prev|next))?$/);if(articleMatch&&req.method==='GET'){let a=articles.find(x=>x.id===decodeURIComponent(articleMatch[1]));if(!a)return json(res,404,{error:'文章不存在'},origin);if(articleMatch[2]){const list=articles.filter(x=>x.mp_id===a.mp_id&&x.status!=='deleted').sort((x,y)=>y.publish_time-x.publish_time),i=list.indexOf(a);a=list[i+(articleMatch[2]==='prev'?1:-1)];if(!a)return json(res,406,{code:40402,message:'没有相邻文章'},origin)}return json(res,200,{code:0,data:a},origin)}
  const refresh=p.match(/^\/articles\/([^/]+)\/refresh$/);if(refresh&&req.method==='POST'){const id=`refresh-${refresh[1]}`;tasks.set(id,{task_id:id,status:'pending'});return json(res,200,{code:0,data:tasks.get(id),message:'已开始刷新，请稍后查看'},origin)}
  const refreshTask=p.match(/^\/articles\/refresh\/tasks\/(.+)$/);if(refreshTask&&req.method==='GET'){const task=tasks.get(refreshTask[1]);if(task?.status==='pending')task.status='completed';return json(res,200,{code:0,data:task},origin)}
  if(articleMatch&&req.method==='DELETE'){const a=articles.find(x=>x.id===decodeURIComponent(articleMatch[1]));if(a)a.status='deleted';return json(res,200,{code:0,message:'文章已标记为删除'},origin)}
  if(p==='/sys/info')return json(res,200,{code:0,data:{wx:{login:mockLogin,info:mockLogin?{nickname:'模拟微信账号'}:null,expiry_time:null},article_sync:{...articleSync}}},origin)
  if(p==='/auth/qr/code'&&req.method==='GET'){qrVersion++;qrExpires=now()+60;mockScanned=false;return json(res,200,{code:0,data:{is_exists:true,version:qrVersion,expires_at:qrExpires}},origin)}
  if(p==='/auth/qr/status'&&req.method==='GET'){const state={login_status:mockLogin,qr_code:true,scanned:mockScanned,version:qrVersion,expires_at:qrExpires,code:`/static/wx_qrcode.png?v=${qrVersion}`};return json(res,200,{code:0,data:state},origin)}
  if(p==='/mock/auth'&&req.method==='POST'){const data=await body(req);if(data.action==='scan')mockScanned=true;if(data.action==='confirm'&&mockScanned)mockLogin=true;const state={login_status:mockLogin,qr_code:true,scanned:mockScanned,version:qrVersion,expires_at:qrExpires};return json(res,200,{code:0,data:state},origin)}
  if(p==='/auth/qr/refresh'&&req.method==='POST'){qrVersion++;qrExpires=now()+60;mockScanned=false;return json(res,200,{code:0,data:{version:qrVersion,expires_at:qrExpires},message:'二维码已刷新'},origin)}
  if((p==='/auth/qr/over'||p==='/auth/wechat/logout')&&req.method==='POST'){if(p.endsWith('logout'))mockLogin=false;return json(res,200,{code:0,message:'演示状态已清理'},origin)}
  if(p==='/tools/export/list'&&req.method==='GET'){const mpId=u.searchParams.get('mp_id')||'';return json(res,200,{code:0,data:exports.filter(item=>!mpId||item.mp_id===mpId)},origin)}
  if(p==='/tools/export/articles'&&req.method==='POST'){const data=await body(req);if(data.export_docx||data.export_pdf)return json(res,422,{code:422,message:'预览仅支持 Markdown、JSON、CSV，DOCX/PDF 需真实数据模式'},origin);const format=['md','json','csv'].find(value=>data[`export_${value}`])||'md',filename=`preview-${exports.length+1}.${format}`,type={md:'text/markdown; charset=utf-8',json:'application/json',csv:'text/csv; charset=utf-8'}[format],content=format==='json'?JSON.stringify({articles:data.doc_id||[]}):format==='csv'?'title,id\n预览文章,demo-1-1\n':'# 公众号预览导出\n';exportFiles.set(filename,{content,type});exports.unshift({filename,path:filename,size:content.length,created_time:new Date().toISOString(),mp_id:data.mp_id||''});return json(res,200,{code:0,data:{filename,message:'导出任务已完成'}},origin)}
  if(p==='/tools/export/delete'&&req.method==='DELETE'){const data=await body(req),index=exports.findIndex(x=>x.path===data.filename||x.filename===data.filename);if(index>=0){exportFiles.delete(exports[index].path);exports.splice(index,1)}return json(res,200,{code:0,data:{filename:data.filename}},origin)}
  const syncStatus=p.match(/^\/mps\/update\/tasks\/([^/]+)$/);if(syncStatus&&req.method==='GET'){const task=syncTasks.get(decodeURIComponent(syncStatus[1]));if(!task)return json(res,404,{code:40404,message:'任务不存在'},origin);if(task.status==='queued'){task.status='running';task.message='正在抓取文章'}else if(task.status==='running'){if(syncMode==='rate-limit'){articleSync.cooldown_until=now()+1800;articleSync.recent_error_code=200013;articleSync.recent_error_message='微信请求频率受限';for(const pending of syncTasks.values())if(pending.status==='queued'||pending.status==='running')Object.assign(pending,{status:'blocked',code:200013,message:'微信请求频率受限，请在冷却结束后手动重试',cooldown_until:articleSync.cooldown_until});activeSyncBySource.clear()}else if(syncMode==='network'){Object.assign(task,{status:'failed',code:50200,message:'微信网络请求失败'});activeSyncBySource.delete(task.mp_id)}else if(syncMode==='unauthorized'){Object.assign(task,{status:'failed',code:40101,message:'微信公众号授权已失效，请重新扫码授权'});mockLogin=false;activeSyncBySource.delete(task.mp_id)}else{const source=sources.find(s=>s.id===task.mp_id);if(source&&emptyMode&&articles.length===0){for(let i=0;i<10;i++)articles.push({id:`empty-${i+1}`,title:`${source.mp_name}：自动获取文章 ${i+1}`,mp_id:source.id,mp_name:source.mp_name,publish_time:now()-i*3600,summary:'空库更新后生成的预览文章',content:`# 自动获取文章 ${i+1}`,url:`https://example.com/empty/${i+1}`,has_content:true,status:'active',is_read:0,is_favorite:0,favorite_at:null});emptyMode=false;task.added=10}else task.added=0;task.status='succeeded';task.message=task.added?'抓取完成':'抓取完成，没有新增文章';activeSyncBySource.delete(task.mp_id)}}return json(res,200,{code:0,data:task},origin)}
  const update=p.match(/^\/mps\/update\/([^/]+)$/);if(update&&req.method==='GET'){const id=decodeURIComponent(update[1]),source=sources.find(s=>s.id===id);if(!source)return json(res,200,{code:40401,message:'请选择一个公众号'},origin);if(id==='MP_WXS_')return json(res,200,{code:40003,message:'公众号标识不完整，请重新添加'},origin);const activeId=activeSyncBySource.get(id);if(activeId)return json(res,200,{code:0,data:{list:[],total:0,mps:source,...syncTasks.get(activeId)}},origin);const task_id=`sync-${++syncSequence}`,blocked=articleSync.cooldown_until>now(),task={task_id,mp_id:id,status:blocked?'blocked':'queued',code:blocked?200013:0,message:blocked?'微信请求频率受限，请在冷却结束后手动重试':'任务已排队',cooldown_until:blocked?articleSync.cooldown_until:0};syncTasks.set(task_id,task);if(!blocked)activeSyncBySource.set(id,task_id);return json(res,200,{code:0,data:{list:[],total:0,mps:source,...task}},origin)}
  const sourceItem=p.match(/^\/mps\/([^/]+)$/);if(sourceItem&&req.method==='PUT'){const source=sources.find(s=>s.id===decodeURIComponent(sourceItem[1]));if(source)source.status=Number((await body(req)).status);return json(res,200,{code:0,data:source},origin)}
  if(sourceItem&&req.method==='DELETE'){const i=sources.findIndex(s=>s.id===decodeURIComponent(sourceItem[1]));if(i>=0)sources.splice(i,1);return json(res,200,{code:0,data:{id:sourceItem[1]}},origin)}
  if(p==='/mps'&&req.method==='POST'){const data=await body(req),id=`demo-added-${++sourceSequence}`,source={id,faker_id:data.mp_id,mp_name:data.mp_name,mp_cover:data.avatar,mp_intro:data.mp_intro,status:1,article_count:0},task_id=`sync-${++syncSequence}`,blocked=articleSync.cooldown_until>now(),sync_task={task_id,mp_id:id,status:blocked?'blocked':'queued',code:blocked?200013:0,message:blocked?'微信请求频率受限，请在冷却结束后手动重试':'任务已排队',cooldown_until:blocked?articleSync.cooldown_until:0};sources.unshift(source);syncTasks.set(task_id,sync_task);if(!blocked)activeSyncBySource.set(id,task_id);return json(res,200,{code:0,data:{...source,sync_task}},origin)}
  if(p==='/mps/by_article'&&req.method==='POST')return json(res,200,{code:0,data:{mp_info:{mp_name:'文章中的公众号',logo:'',biz:Buffer.from('99').toString('base64')},mp_id:'MP_WXS_preview'}},origin)
  if(p==='/mps/featured/article'&&req.method==='POST'){const data=await body(req);if(!data.url)return json(res,422,{error:'请输入文章链接'},origin);const id=`featured-${tasks.size+1}`,articleId=`featured-article-${tasks.size+1}`;articles.unshift({id:articleId,title:'单篇收录的预览文章',mp_id:'demo-1',mp_name:sources[0].mp_name,publish_time:now(),summary:'单篇收录完成',content:'# 单篇收录完成',url:data.url,has_content:true,status:'active',is_read:0,is_favorite:0,favorite_at:null});tasks.set(id,{task_id:id,url:data.url,status:'success',article_id:articleId,message:'预览收录完成'});return json(res,200,{code:0,data:tasks.get(id)},origin)}
  const task=p.match(/^\/mps\/featured\/article\/tasks\/(.+)$/);if(task&&req.method==='GET')return json(res,200,{code:0,data:tasks.get(task[1])},origin)
  if(p==='/export/mps/export'&&req.method==='GET'){res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="subscriptions.csv"','access-control-allow-origin':origin});return res.end('name,id\n演示公众号,demo-1\n')}
  if(p==='/export/mps/opml'&&req.method==='GET'){res.writeHead(200,{'content-type':'text/x-opml; charset=utf-8','content-disposition':'attachment; filename="subscriptions.opml"','access-control-allow-origin':origin});return res.end('<?xml version="1.0"?><opml version="2.0"><body><outline text="演示公众号" xmlUrl="demo-1"/></body></opml>')}
  if(p==='/export/mps/import'&&req.method==='POST'){const id=`demo-imported-${++sourceSequence}`;sources.unshift({id,faker_id:Buffer.from(id).toString('base64'),mp_name:'导入的公众号',mp_cover:'',mp_intro:'来自 CSV 导入',status:1,article_count:0});return json(res,200,{code:0,data:{imported:1},message:'导入完成'},origin)}
  json(res,404,{error:'预览接口不存在'},origin)
 })
}
export async function listenPreviewHost(port=0){const server=createPreviewHost();await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve)});return server}
if(import.meta.url===`file://${process.argv[1]?.replace(/\\/g,'/')}`){const port=Number(process.env.WRSS_PREVIEW_PORT||43202);listenPreviewHost(port).then(server=>{console.log(`WRSS preview host listening at http://127.0.0.1:${server.address().port}`);const stop=()=>server.close(()=>process.exit(0));process.on('SIGINT',stop);process.on('SIGTERM',stop)})}
